name: Reusable package standard check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  standard:
    name: Package standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout package repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Checkout MortalKiller package standard
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          repository: mortalkiller/filament-package-template
          ref: ${{ github.repository == 'mortalkiller/filament-package-template' && github.ref_name || '1.x' }}
          persist-credentials: false
          path: .mortal-package-standard

      - name: Run package standard checker
        shell: bash
        run: |
          if [[ "$GITHUB_REPOSITORY" == "mortalkiller/filament-package-template" ]]; then
            php .mortal-package-standard/tools/package-standard-check.php --skip-plumb "$GITHUB_WORKSPACE"
          else
            php .mortal-package-standard/tools/package-standard-check.php "$GITHUB_WORKSPACE"
          fi
