name: Package standard

on:
  pull_request:
  push:
    branches:
      - main
      - '1.x'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: standard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  standard:
    uses: ./.github/workflows/reusable-standard-check.yml
